version: "3.8"

services:
 rabbitmq:
  image: rabbitmq:3.13-rc-management
  hostname: rabbitmq
  restart: always
  environment:
   - RABBITMQ_DEFAULT_USER=test_user
   - RABBITMQ_DEFAULT_PASS=rmpassword
   - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  volumes:
   - ./rabbitmq:/var/lib/rabbitmq
  ports:
   - 15673:15672
   - 5673:5672